package codegen

type Engine struct {
	// Name is the name display to the user
	Name string
	// Desc is also display to the user
	Desc string
	// Gen is the custom code [Generator] implementation for this Engine
	Gen Generator
	// Ephemeral is true if the code generated by the Engine does not to be stored
	// on disk
	Ephemeral bool
	// Extension is the file extension used for non-Ephemeral Engines
	Extension string
	// Exec is the custom code [Executor] implementation for this Engine
	Exec Executor
	// Executable is true if the generated can be executed by Skol directly;
	// note that this is mostly meant for transpilers and not actual compilation.
	Executable bool
}
